# Generated by Django 3.2.23 on 2023-11-08 15:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Variants',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(blank=True, max_length=100, null=True)),
                ('Age', models.IntegerField(blank=True, null=True)),
                ('Stage', models.IntegerField(blank=True, null=True)),
                ('Description', models.CharField(blank=True, max_length=50, null=True)),
                ('Sequencer', models.CharField(blank=True, max_length=100, null=True)),
                ('cDNA_variant', models.CharField(blank=True, max_length=100, null=True)),
                ('protein_variant', models.CharField(blank=True, max_length=100, null=True)),
                ('genomic_variant', models.CharField(blank=True, max_length=100, null=True)),
                ('Gene', models.CharField(blank=True, max_length=50, null=True)),
                ('Classification', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalVariants',
            fields=[
                ('id', models.IntegerField(blank=True, db_index=True)),
                ('Name', models.CharField(blank=True, max_length=100, null=True)),
                ('Age', models.IntegerField(blank=True, null=True)),
                ('Stage', models.IntegerField(blank=True, null=True)),
                ('Description', models.CharField(blank=True, max_length=50, null=True)),
                ('Sequencer', models.CharField(blank=True, max_length=100, null=True)),
                ('cDNA_variant', models.CharField(blank=True, max_length=100, null=True)),
                ('protein_variant', models.CharField(blank=True, max_length=100, null=True)),
                ('genomic_variant', models.CharField(blank=True, max_length=100, null=True)),
                ('Gene', models.CharField(blank=True, max_length=50, null=True)),
                ('Classification', models.CharField(blank=True, max_length=50, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical variants',
                'verbose_name_plural': 'historical variantss',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
